# Generated by Django 3.1.4 on 2021-05-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210502_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followings',
            name='following_num',
        ),
        migrations.AddField(
            model_name='user',
            name='following_num',
            field=models.IntegerField(default=0),
        ),
    ]
