# Generated by Django 3.1.4 on 2021-05-06 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210502_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followings',
            old_name='following_users',
            new_name='followed_by',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='sender',
            new_name='user',
        ),
        migrations.AddField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='Liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
