# Generated by Django 3.1.4 on 2021-08-28 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210506_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='followings',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
