# Generated by Django 3.1.4 on 2021-09-02 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_followings_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followings',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='fwby_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followings',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='fwing_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
